# Generated by Django 4.2.1 on 2024-11-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0005_delivery_ordercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercard',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
