# Generated by Django 4.2.1 on 2024-12-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0006_ordercard_net_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
