# Generated by Django 4.2.1 on 2024-12-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0008_ordercard_total_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercard',
            old_name='total_item_price',
            new_name='total_items_price',
        ),
    ]
