# Generated by Django 4.2.1 on 2024-12-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0009_rename_total_item_price_ordercard_total_items_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercard',
            name='total_items_price',
        ),
    ]
