# Generated by Django 4.2.1 on 2024-12-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0010_remove_ordercard_total_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_items_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_items_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
