# Generated by Django 4.2.1 on 2024-12-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0011_orderitem_total_items_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='SELLER', max_length=10),
        ),
    ]
