# Generated by Django 4.2.1 on 2024-12-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0012_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_lower_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_upper_limit',
            field=models.IntegerField(default=0),
        ),
    ]
