# Generated by Django 4.2.1 on 2024-12-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0014_product_inventory_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exported_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='imported_qty',
            field=models.IntegerField(default=0),
        ),
    ]
