# Generated by Django 4.2.1 on 2024-10-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
